# Generated by Django 6.0.2 on 2026-03-06 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='profileImage',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='foto de perfil'),
        ),
    ]
