# Generated by Django 6.0.2 on 2026-03-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usuario_profileimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='bannerImage',
            field=models.ImageField(blank=True, null=True, upload_to='profile_banners/', verbose_name='banner de perfil'),
        ),
    ]