name: Main CI

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main", "develop"]
  workflow_dispatch:

jobs:
  django-tests:
    uses: ./.github/workflows/django.yml

  docker-build:
    uses: ./.github/workflows/docker-image.yml
